# Generated by Django 5.2.4 on 2025-10-21 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_email",
                    models.EmailField(
                        max_length=254,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid email address.",
                                regex="\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,7}\\b",
                            )
                        ],
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid email address.",
                                regex="\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,7}\\b",
                            )
                        ],
                    ),
                ),
                ("token", models.TextField(unique=True)),
                ("access_url", models.URLField()),
                ("is_accepted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("repo_url", models.URLField(max_length=500)),
                ("branch", models.CharField(default="main", max_length=100)),
                ("is_private", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_doc_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ssh_key_path",
                    models.CharField(default="keys/public_key.pem", max_length=255),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="projects_app.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "repo_url", "branch")},
            },
        ),
    ]
