# Generated by Django 5.1.3 on 2025-10-04 04:55

import django.db.models.deletion
import extras_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=512)),
                ('http_method', models.CharField(max_length=10)),
                ('request_payload', extras_app.models.CompressedJSONField(blank=True, null=True)),
                ('response_payload', extras_app.models.CompressedJSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latency', models.FloatField()),
                ('ip_address', models.GenericIPAddressField()),
                ('headers', extras_app.models.CompressedJSONField(blank=True, null=True)),
                ('service', models.CharField(max_length=128)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
