# Generated by Django 5.1.3 on 2025-10-03 10:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,7}\\b')])),
                ('to_email', models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,7}\\b')])),
                ('token', models.TextField(unique=True)),
                ('access_url', models.URLField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
